# set parameters for plain text
fontSize: 16
fontFamily: Arial
useLigatures: false
theme: vs-light

# set parameters for code
codeFontSize: 14
codeFontFamily: Consolas
codeUseLigatures: true
codeTheme: vs-dark